os: linux
arch:
 - amd64
 - ppc64le
language: python
dist: xenial
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - git fetch --tags
  - pip install coveralls tox-travis

  # generate some reflog for tests
  - ./init-tests-after-clone.sh

script:
  - tox

after_success:
  - coveralls
